name: iOS starter workflow
on: [push]

jobs:
    build:
        name: Build and Test default scheme using any available iPhone simulator
        runs-on: macos-latest

steps:
    run: echo Test One Worked!
