name: iOS starter workflow
on: [push]

jobs:
    build:
        name: Build and Test default scheme using any available iPhone simulator
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: swift-actions/setup-swift@v1
              with:
                swift-version: "5.7.2"
            - name: Print Hello World
              run: echo 'Hello World'
            - name: testing ... iPhone 15
              run: >-
                xcodebuild test -workspace Plogging.xcodeproj/project.xcworkspace
                -scheme Plogging -destination 'platform=iOS Simulator,name=iPhone 15,OS=13.7'
