name: iOS starter workflow
on: [push]

jobs:
    build:
        name: Build and Test default scheme using any available iPhone simulator
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: swift-actions/setup-swift@v1
              with:
                swift-version: "5.7.2"
              with:
                xcode-version: "15.0.1"
            - name: Print a greeting
              run: echo 'Hello World'
            - name: Swift Package
              run: swift package init --type library
            - name: Swift version
              run: swift --version
            - name: Swift Build
              run: swift build
            - name: Swift Tests
              run: swift test
            - name: Swift Unit Tests
              run: swift unittests
