name: iOS starter workflow
on: [push]

jobs:
    build:
        name: Build and Test default scheme using any available iPhone simulator
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
              with:
                swift-version: "5.7.2"
            - uses: swift-actions/setup-swift@v4
            - name: Print a greeting
              run: echo 'Hello World'
            - name: Swift version
              run: swift --version
            - name: Swift Build
              run: swift build
